import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

import { EventraEngine } from "../../src/core/EventraEngine";
import { EventraConfig } from "../../src/types";

const CONFIG: EventraConfig = {
  apiKey: "",
  endpoint: "",
  events: [],
  functionWrappers: [],
  sync: {
    include: ["**/*.ts"],
    exclude: ["node_modules", "dist", ".next", ".git"],
  },
};

function makeProject() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "nuxt-auto-import-"));
  return {
    root,
    cleanup: () => fs.rmSync(root, { recursive: true, force: true }),
  };
}

function writeFile(root: string, rel: string, content: string): string {
  const abs = path.join(root, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  return abs;
}

const SDK_SOURCE = `
declare module "@eventra_dev/eventra-sdk" {
  export interface TrackOptions { userId?: string }
  export class Eventra {
    constructor(config: { apiKey: string });
    track(event: string, options?: TrackOptions): void;
  }
}
`;

/**
 * Mirrors a real Nuxt project: a composable file with a real \`sdk.track()\`
 * call, a \`.nuxt/imports.d.ts\`-style ambient global generated by Nuxt's
 * auto-import (unimport) for that composable, and a page that calls it with
 * no \`import\` statement — exactly how Nuxt's own build pipeline presents it
 * to the type checker (and to any static analysis running against the
 * project's own tsconfig.json).
 */
describe("Nuxt-style auto-import compatibility", () => {
  it("resolves a wrapper reached only through a Nuxt-generated ambient auto-import global", async () => {
    const { root, cleanup } = makeProject();
    try {
      writeFile(root, "tsconfig.json", JSON.stringify({
        compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "Bundler", skipLibCheck: true },
        include: ["**/*.ts", ".nuxt/imports.d.ts"],
      }));
      writeFile(root, "eventra-sdk-shim.d.ts", SDK_SOURCE);
      const composable = writeFile(
        root,
        "composables/useAnalytics.ts",
        `
          import { Eventra } from "@eventra_dev/eventra-sdk";
          const sdk = new Eventra({ apiKey: "k" });
          export function trackFeature(event: string): void {
            sdk.track(event);
          }
        `,
      );
      writeFile(
        root,
        ".nuxt/imports.d.ts",
        `
          export {}
          declare global {
            const trackFeature: typeof import("../composables/useAnalytics")["trackFeature"];
          }
        `,
      );
      const page = writeFile(
        root,
        "pages/index.ts",
        `
          trackFeature("nuxt.auto_import_event");
        `,
      );

      const engine = new EventraEngine(root);
      await engine.runFullAnalysis([composable, page], CONFIG);

      expect(engine.getAllFunctionWrappers()).toContain("trackFeature");
      expect(engine.getAllEvents()).toContain("nuxt.auto_import_event");
    } finally {
      cleanup();
    }
  });

  it("also resolves the dotted-qualifier ambient form (typeof import(...).name)", async () => {
    const { root, cleanup } = makeProject();
    try {
      writeFile(root, "tsconfig.json", JSON.stringify({
        compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "Bundler", skipLibCheck: true },
        include: ["**/*.ts", ".nuxt/imports.d.ts"],
      }));
      writeFile(root, "eventra-sdk-shim.d.ts", SDK_SOURCE);
      const composable = writeFile(
        root,
        "composables/useAnalytics.ts",
        `
          import { Eventra } from "@eventra_dev/eventra-sdk";
          const sdk = new Eventra({ apiKey: "k" });
          export function trackFeature(event: string): void {
            sdk.track(event);
          }
        `,
      );
      writeFile(
        root,
        ".nuxt/imports.d.ts",
        `
          export {}
          declare global {
            const trackFeature: typeof import("../composables/useAnalytics").trackFeature;
          }
        `,
      );
      const page = writeFile(root, "pages/index.ts", `trackFeature("nuxt.dotted_event");`);

      const engine = new EventraEngine(root);
      await engine.runFullAnalysis([composable, page], CONFIG);

      expect(engine.getAllFunctionWrappers()).toContain("trackFeature");
      expect(engine.getAllEvents()).toContain("nuxt.dotted_event");
    } finally {
      cleanup();
    }
  });
});
